---
- hosts: all
  connection: local


  vars_files:
    - default.config.yml


  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']


  roles:
    - role: elliotweiser.osx-command-line-tools
      force_install: no # if yes, removes installed version
      tags: ['always']

    - role: geerlingguy.homebrew
      tags: ['homebrew']

    - role: dotfiles
      when: configure_dotfiles | bool
      tags: ['dotfiles']


  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/sudoers.yml
      when: configure_sudoers | bool

    - include_tasks: tasks/terminal.yml
      when: configure_terminal | bool

    - include_tasks: tasks/osx.yml
      when: configure_osx | bool
      tags: ['osx']

    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
